services:
  web:
    build: .
    ports:
      - 3636:3636
    secrets:
      - secret.json
      - mail-secret.json
    env_file: .env.docker
secrets:
    secret.json:
      file: ./secret.json
    mail-secret.json:
      file: ./mail-secret.json