name: test pull request

on: pull_request

jobs:
  build:
    env:
      IN_GITHUB_ACTION: YES
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 16
      - run: yarn install --froze-lockfile
      - name: Retrieve the secret.json and decode it to a file
        env:
          SECRET_JSON: ${{ secrets.SECRET_JSON }}
        run: echo $SECRET_JSON | tee > exam-schedules-api/secret.json exam-schedules-lib/secret.json
      - run: yarn build
      - run: yarn test-api
      - run: yarn test-lib